#Verilog


##--------------------------------Makefile------------------------------------
##
##				 Copyright (C) 2020 by
##				 Belinda Brown Ramírez
##				 timna.brown@ucr.ac.cr
##
##-----------------------------------------------------------------------------


# Making verilog makefile
# Makefile to simulate Verilog HDL designs under OSX.

###### IMPORTANT !!!!!!!!!
###### NEED TO BE READED
# Please note that the gtkwave command referes to a specific
# path so removed or just do in the command line console:
# <folder path>$ gtkwave <vcd file with the vcd extention>

# 							Makefile logic:
# To create this file you need these files:
# $ @ replace left
# $ ^ right

#******************************************************************************
#										TARGETS
#******************************************************************************
### 						YOSYS
# To generate the structural design of the
# behavioral design automatically through synthesis
#It is defined as a roughly RTL (Register Transfer Level)
#synthesizer that allows you to convert the HDL (Hardware
# Description Language) code into an electronic scheme.
# Coming to show the components connected to each other what
# is usually called RTL network list which is associated with
# the level of registry transfer. Considering that what it allows
# is to model a synchronous digital circuit in terms of digital signal
# flow (this being data) relating it to the hardware registers and the
# logical operations that are carried out in each signal.

#******************************************************************************
HERE = ./
A_SRC = ./source/

#******************************************************************************
qflow:
	qflow synthesize place route arbiter.v
#******************************************************************************

.PHONY: sta
sta:
	qflow sta arbiter


#******************************************************************************
############ CLEAN FOR ALL
.PHONY: clean 
clean:
	rm -rf $(A_SRC)*.par $(A_SRC)*.sh $(A_SRC)*.ys $(HERE)*.sh $(HERE)*.log ./layout/* ./synthesis/* $(A_SRC)*.blif


#******************************************************************************

